AddonId: Lithium_c2635228-430a-4ef0-9a0f-0219e1e1c53c
Packages:
  - Version: 1.0.0
    RequiredApiVersion: 2.6.0
    ReleaseDate: 2024-01-18
    PackageUrl: https://github.com/lscholte/Lithium/releases/download/1.0/Lithium_c2635228-430a-4ef0-9a0f-0219e1e1c53c_1_0_0.pthm
    Changelog:
      - Forked from Helium theme
      - Modified grid view hover buttons to be more visible